---
title: "*Schiedea* scent evolution"
author: "[John Powers](http://sites.uci.edu/powers/)"
date: "`r Sys.Date()`"
output:
  html_document:
  self_contained: no
lib_dir: libs
code_folding: hide
toc: yes
toc_float: TRUE
editor_options: 
  chunk_output_type: console
---
  
<style type="text/css">
.main-container { max-width: 1000px; margin-left: 0; margin-right: auto; }
img{ max-width:200%; height: auto; }
td, th { padding : 6px }
</style>
  
```{r setup, message=FALSE}
library(tidyverse)
library(vegan)
library(knitr)
library(reshape2)
library(viridis)
knitr::opts_chunk$set(comment="", cache=T, warning = F, message = F, 
                      fig.path = "images/", dev="svglite", dev.args=list(fix_text_size=FALSE), fig.height=8, fig.width=8)
options(digits=4) # for kables
source("read_shimadzu.R")
```

```{r read_scents}
# sch.data <- read.shimadzu("../Schiedea/schiedea190801.txt")
# sch.data2 <- read.shimadzu("../Schiedea/Schiedea_190814.txt")
# sch.data <- bind_rows(sch.data, sch.data2)
# save(sch.data, file="data/RMBL_GCMS/schiedea_190801_190814.Rdata")
# batches.212223 <- c("PG_VF_210826.txt", "PG_Ihyb_220806_1.txt", "Ihyb_SCH_230822b.txt",
#                     "Ihyb_SCH_230823a.txt", "Ihyb_SCH_230823b.txt", "PFOL_SCH_230822a.txt","SCH_230829a.txt")
# sch.data.212223 <- "../RMBL Batches/" %>% paste0(batches.212223) %>% set_names(batches.212223) %>%
#   map_dfr(read.shimadzu, .id="batch") 
# save(sch.data.212223, file="data/RMBL_GCMS/schiedea_212223.Rdata")
load("data/RMBL_GCMS/schiedea_212223.Rdata")
sch.data.212223 %>% count(batch, Filename) %>% filter(str_detect(Filename, "SCH"))
load("data/RMBL_GCMS/schiedea_190801_190814.Rdata")
sch.data <- bind_rows(sch.data, sch.data.212223)

sch.all <- dcast(sch.data, Filename~Name, sum, value.var="Area")
rownames(sch.all) <- sch.all[,1]
sch.all[,1] <- NULL
sch.cut <- sch.all[,colSums(sch.all)>4e6]
```


```{r kmeans}
set.seed(1)
km <- kmeans(decostand(sch.cut, "log"), centers=30, nstart=3)
isblank <- grepl("Blank|Bakeout", rownames(sch.cut))#if original FileName says blank
table(km$cluster, isblank)
kblank <- km$cluster == which.max(table(km$cluster, isblank)[,2])

load("data/RMBL_GCMS/markes_sequence230908_2023.rda") #2023 only
sequ.summary.23 <- sequ.file %>% 
  select(c(sequence.start, Desorb.Start.Time, CreationTime, eithertime, status, Tube, markes_n,
           GC_n, either_n, markes_GC, create_desorb,  FileName, user, FullName, id, fuzzy_n)) %>% #columns needed for annotating verdicts
  arrange(sequence.start, markes_n, eithertime) %>%
  mutate(desorb.Start.diff = c(NA, diff(Desorb.Start.Time)))

# load("../Inventory/markes_sequence.rda") #through 2022, from markes_sequence.R
# save(sequ.summary, file="data/RMBL_GCMS/sequ_summary221006.rda")
load("data/RMBL_GCMS/sequ_summary221006.rda") #2022 and earlier
sequ.summary <- bind_rows(sequ.summary, sequ.summary.23)

Powers <- grepl("Powers RMBL Data", sequ.summary$FullName, fixed=T) | grepl("SCH_", sequ.summary$FileName, fixed=T)
schiedea.ids <- sequ.summary %>% filter(Powers) %>% select(id) %>% unique %>% na.omit
schgc <- sequ.summary %>% filter(id %in% schiedea.ids$id | Powers)
schgc$vial <- as.integer(str_match(schgc$FileName, "_V(\\d{1,3})")[,2])
schgc$dupe <- !is.na(schgc$vial) & schgc$vial %in% schgc$vial[duplicated(schgc$vial)]
sch.km <- data.frame(FileName=row.names(sch.cut), 
                     nameBlank= isblank, Mixup= isblank!=kblank, kBlank=kblank,
                     Cluster=km$cluster)[match(schgc$FileName, row.names(sch.cut)),]
schgc <- cbind(schgc, sch.km[,-1])
rownames(schgc) <- 1:nrow(schgc)

notebook <- read.delim("data/RMBL_GCMS/leak_notebook.csv")
schgc <- cbind(schgc, notebook[match(schgc$vial, as.integer(as.character(notebook$Vial)), incomparables=NA),-4])
schgc$TubeMatch <- schgc$Tube == schgc$SteelTube
write.csv(schgc, "data/RMBL_GCMS/schiedea_all230908.csv")

with(sch.km, table(kBlank, nameBlank))
```

```{r kmeans_pca}
pca.sch.cut <- rda(sqrt(sch.cut))
ordiplot(pca.sch.cut, type = "n")
text(pca.sch.cut, display="sites", labels=km$cluster, col=kblank+1,cex=0.5 )
points(pca.sch.cut, display="sites", col=ifelse(kblank, "black", rainbow(k)[km$cluster]), pch=as.integer(isblank)+1)
```

```{r schgc}
#match up with metadata
#sampl <-gs_title("Schiedea Volatiles Sampling")
#sampl <- "1DhjN1O3tvAwG1NnCp9oUSEVxoNKgQyperArin2zbsFY"
sampl <- "data/RMBL_GCMS/Schiedea Volatiles Sampling - Samples.tsv"
s <- read_tsv(sampl, col_types = cols(.default = col_character(),
                                     Flow = col_double(),
                                     Mass = col_double(),
                                     RunDate = col_date(format = ""),
                                     SampleDate = col_date(format = ""),
                                     Start = col_time(format = ""),
                                     Stop = col_time(format = ""),
                                     Equi = col_double(),
                                     Duration = col_double(),
                                     Total = col_double()
))
s.nr <- s[s$GC=="NR",]
s.nr$Vial <- as.integer(s.nr$Vial)
s.nr$DN <- factor(ifelse(s.nr$Start > 16*60*60, "Night", "Day"))


sort(union(s.nr$Vial, schgc$vial2))
sort(setdiff(s.nr$Vial, schgc$vial2)) #not run yet
sort(setdiff(schgc$vial2, s.nr$Vial)) #run but not entered  
broken <- c(52,53,56,86,117,124,125,129,174) #broken traps - not run
empty <- c(7,16,18,28,40,313,314,315,316) # presumed clean - run
notrun <- c(5,8,21,30,33,50,51,55,57,64,66,74,75,80,81,82,83,84,88,89,91,95,100,102,103,104,107,108,109,11,12,22,23,24,25,26,58,59,60,61,62,63,58,92,94,96,97,98,9, 90, 79, 87, 72, 99)
setdiff(setdiff(setdiff(s.nr$Vial, schgc$vial2), broken), notrun)

#read back the verdicts
#library(googlesheets4)
#rmbl <- gs_title("Schiedea RMBL GC-MS Inventory")
#schgc.verdict <- read_sheet("1_rNiQ3IwKIKQhfxZTBJbKU14ed6L1rGQpe7e_ttJl6Y", na="NA", guess_max=2000)
schgc.verdict19 <- read_tsv("data/RMBL_GCMS/Schiedea RMBL GC-MS Inventory - schiedea_all.tsv") %>% 
  mutate(across(all_of(c("sequence.start", "Desorb.Start.Time", "CreationTime", "eithertime")), ymd_hms),
         create_desorb = duration(create_desorb),
         ApproxDate = as.character(ApproxDate)) %>% 
  filter(index <= 841) #knock off a couple blanks that don't align

which(year(schgc$eithertime) > 2020)
schgc.verdict212223 <- schgc[c(106:142,910:991),] %>% #119 recent rows, was 842:891
  left_join(s.nr %>% select(vial3=Vial,FileName=Filename) %>%  filter(vial3 >=700))  #TODO hack to paste in vial numbers of the new samples
schgc.verdict <- bind_rows(schgc.verdict19, schgc.verdict212223)

#TODO get verdicts and schgc to match
sum(schgc.verdict$FileName != schgc$FileName, na.rm=T)
nrow(schgc.verdict)
nrow(schgc) #longer by 31
setdiff(schgc.verdict$FileName, schgc$FileName) #29 in verdicts, not schgc (all from 2019)
setdiff(schgc$FileName, schgc.verdict$FileName) #2 blanks in schgc, not verdicts (knocked off above)
plot(match(schgc$FileName, schgc.verdict$FileName))
plot(match(schgc.verdict$FileName, schgc$FileName))

schgc$verdict <- schgc.verdict$verdict #assumes the verdicts are in the same row order
schgc$FileName2 <- ifelse(is.na(schgc.verdict$sample), schgc$FileName, schgc.verdict$sample)
schgc$vial2 <- as.integer(str_match(schgc$FileName2, "_V(\\d{1,3})")[,2])
schgc$vial2 <- coalesce(schgc$vial2, schgc.verdict$vial3)#TODO hack for new samples
schgc$dupe2 <- !is.na(schgc$vial2) & schgc$vial2 %in% schgc$vial2[duplicated(schgc$vial2)]
#schgc.use <- schgc[!(schgc$verdict %in% c("alreadyrun", "empty","leak-blank", "notmine", "notrun", "skip-blank", "skip-notrun")),]

sv.all <- merge(s.nr, schgc, by.x = "Vial", by.y="vial2", all.x = T, all.y = T)
write.csv(sv.all, "s.nr.schgc220806.csv")
```

